name: uidesignbasic
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  audioplayers: ^0.15.1
  http: ^0.12.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
    - assets/
    - assets/images/


  fonts:
    - family: SourceSansPro
      fonts:
        - asset: fonts/fonts.ttf

    - family: Pacifico
      fonts:
        - asset: fonts/fonts.ttf

    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf


